services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/docker/volumes/postgres-f1-data/_data  
    ports:
      - 5432:5432

  api:
    build:
      context: .
    ports:
      - 5000:80
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres-data:
  