// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(StandingsContext))]
    [Migration("20230211210338_SeedYears")]
    partial class SeedYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandingsYearId")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverId");

                    b.HasIndex("StandingsYearId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("API.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandingsYearId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaceId");

                    b.HasIndex("StandingsYearId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("API.Models.StandingsYear", b =>
                {
                    b.Property<int>("StandingsYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StandingsYearId"));

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StandingsYearId");

                    b.ToTable("StandingsYears");

                    b.HasData(
                        new
                        {
                            StandingsYearId = 1950,
                            Year = 1950
                        },
                        new
                        {
                            StandingsYearId = 1951,
                            Year = 1951
                        },
                        new
                        {
                            StandingsYearId = 1952,
                            Year = 1952
                        },
                        new
                        {
                            StandingsYearId = 1953,
                            Year = 1953
                        },
                        new
                        {
                            StandingsYearId = 1954,
                            Year = 1954
                        },
                        new
                        {
                            StandingsYearId = 1955,
                            Year = 1955
                        },
                        new
                        {
                            StandingsYearId = 1956,
                            Year = 1956
                        },
                        new
                        {
                            StandingsYearId = 1957,
                            Year = 1957
                        },
                        new
                        {
                            StandingsYearId = 1958,
                            Year = 1958
                        },
                        new
                        {
                            StandingsYearId = 1959,
                            Year = 1959
                        },
                        new
                        {
                            StandingsYearId = 1960,
                            Year = 1960
                        },
                        new
                        {
                            StandingsYearId = 1961,
                            Year = 1961
                        },
                        new
                        {
                            StandingsYearId = 1962,
                            Year = 1962
                        },
                        new
                        {
                            StandingsYearId = 1963,
                            Year = 1963
                        },
                        new
                        {
                            StandingsYearId = 1964,
                            Year = 1964
                        },
                        new
                        {
                            StandingsYearId = 1965,
                            Year = 1965
                        },
                        new
                        {
                            StandingsYearId = 1966,
                            Year = 1966
                        },
                        new
                        {
                            StandingsYearId = 1967,
                            Year = 1967
                        },
                        new
                        {
                            StandingsYearId = 1968,
                            Year = 1968
                        },
                        new
                        {
                            StandingsYearId = 1969,
                            Year = 1969
                        },
                        new
                        {
                            StandingsYearId = 1970,
                            Year = 1970
                        },
                        new
                        {
                            StandingsYearId = 1971,
                            Year = 1971
                        },
                        new
                        {
                            StandingsYearId = 1972,
                            Year = 1972
                        },
                        new
                        {
                            StandingsYearId = 1973,
                            Year = 1973
                        },
                        new
                        {
                            StandingsYearId = 1974,
                            Year = 1974
                        },
                        new
                        {
                            StandingsYearId = 1975,
                            Year = 1975
                        },
                        new
                        {
                            StandingsYearId = 1976,
                            Year = 1976
                        },
                        new
                        {
                            StandingsYearId = 1977,
                            Year = 1977
                        },
                        new
                        {
                            StandingsYearId = 1978,
                            Year = 1978
                        },
                        new
                        {
                            StandingsYearId = 1979,
                            Year = 1979
                        },
                        new
                        {
                            StandingsYearId = 1980,
                            Year = 1980
                        },
                        new
                        {
                            StandingsYearId = 1981,
                            Year = 1981
                        },
                        new
                        {
                            StandingsYearId = 1982,
                            Year = 1982
                        },
                        new
                        {
                            StandingsYearId = 1983,
                            Year = 1983
                        },
                        new
                        {
                            StandingsYearId = 1984,
                            Year = 1984
                        },
                        new
                        {
                            StandingsYearId = 1985,
                            Year = 1985
                        },
                        new
                        {
                            StandingsYearId = 1986,
                            Year = 1986
                        },
                        new
                        {
                            StandingsYearId = 1987,
                            Year = 1987
                        },
                        new
                        {
                            StandingsYearId = 1988,
                            Year = 1988
                        },
                        new
                        {
                            StandingsYearId = 1989,
                            Year = 1989
                        },
                        new
                        {
                            StandingsYearId = 1990,
                            Year = 1990
                        },
                        new
                        {
                            StandingsYearId = 1991,
                            Year = 1991
                        },
                        new
                        {
                            StandingsYearId = 1992,
                            Year = 1992
                        },
                        new
                        {
                            StandingsYearId = 1993,
                            Year = 1993
                        },
                        new
                        {
                            StandingsYearId = 1994,
                            Year = 1994
                        },
                        new
                        {
                            StandingsYearId = 1995,
                            Year = 1995
                        },
                        new
                        {
                            StandingsYearId = 1996,
                            Year = 1996
                        },
                        new
                        {
                            StandingsYearId = 1997,
                            Year = 1997
                        },
                        new
                        {
                            StandingsYearId = 1998,
                            Year = 1998
                        },
                        new
                        {
                            StandingsYearId = 1999,
                            Year = 1999
                        },
                        new
                        {
                            StandingsYearId = 2000,
                            Year = 2000
                        },
                        new
                        {
                            StandingsYearId = 2001,
                            Year = 2001
                        },
                        new
                        {
                            StandingsYearId = 2002,
                            Year = 2002
                        },
                        new
                        {
                            StandingsYearId = 2003,
                            Year = 2003
                        },
                        new
                        {
                            StandingsYearId = 2004,
                            Year = 2004
                        },
                        new
                        {
                            StandingsYearId = 2005,
                            Year = 2005
                        },
                        new
                        {
                            StandingsYearId = 2006,
                            Year = 2006
                        },
                        new
                        {
                            StandingsYearId = 2007,
                            Year = 2007
                        },
                        new
                        {
                            StandingsYearId = 2008,
                            Year = 2008
                        },
                        new
                        {
                            StandingsYearId = 2009,
                            Year = 2009
                        },
                        new
                        {
                            StandingsYearId = 2010,
                            Year = 2010
                        },
                        new
                        {
                            StandingsYearId = 2011,
                            Year = 2011
                        },
                        new
                        {
                            StandingsYearId = 2012,
                            Year = 2012
                        },
                        new
                        {
                            StandingsYearId = 2013,
                            Year = 2013
                        },
                        new
                        {
                            StandingsYearId = 2014,
                            Year = 2014
                        },
                        new
                        {
                            StandingsYearId = 2015,
                            Year = 2015
                        },
                        new
                        {
                            StandingsYearId = 2016,
                            Year = 2016
                        },
                        new
                        {
                            StandingsYearId = 2017,
                            Year = 2017
                        },
                        new
                        {
                            StandingsYearId = 2018,
                            Year = 2018
                        },
                        new
                        {
                            StandingsYearId = 2019,
                            Year = 2019
                        },
                        new
                        {
                            StandingsYearId = 2020,
                            Year = 2020
                        },
                        new
                        {
                            StandingsYearId = 2021,
                            Year = 2021
                        },
                        new
                        {
                            StandingsYearId = 2022,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("API.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StandingsYearId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("StandingsYearId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("API.Models.Driver", b =>
                {
                    b.HasOne("API.Models.StandingsYear", "StandingsYear")
                        .WithMany("Drivers")
                        .HasForeignKey("StandingsYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandingsYear");
                });

            modelBuilder.Entity("API.Models.Race", b =>
                {
                    b.HasOne("API.Models.StandingsYear", "StandingsYear")
                        .WithMany("Races")
                        .HasForeignKey("StandingsYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandingsYear");
                });

            modelBuilder.Entity("API.Models.Team", b =>
                {
                    b.HasOne("API.Models.StandingsYear", "StandingsYear")
                        .WithMany("Teams")
                        .HasForeignKey("StandingsYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandingsYear");
                });

            modelBuilder.Entity("API.Models.StandingsYear", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Races");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
